/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.wj.telas;

import br.com.wj.dal.ModuloConexao;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Geyvson
 */
public class TelaDespesas extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tipo;
    String periodo;
    String tipoPeriodo;

    /**
     * Creates new form Despesas
     */
    public TelaDespesas() {

        initComponents();
        conn = ModuloConexao.conectaBD();
        pesquisarDespesa();
        pesquisaRelatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cboMesCadastro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbtMensal = new javax.swing.JRadioButton();
        rbtFixo = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDespesa = new javax.swing.JTable();
        txtPesq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboMesPesq = new javax.swing.JComboBox<>();
        txtSubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        btnSubtotal = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelatorio = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnRelCalcular = new javax.swing.JButton();
        txtDespPagas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDespPendentes = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        rbtRelAmbas = new javax.swing.JRadioButton();
        rbtRelPendente = new javax.swing.JRadioButton();
        rbtRelPaga = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        rbtRelMensal = new javax.swing.JRadioButton();
        cboRelMes = new javax.swing.JComboBox<>();
        rbtRelTodas = new javax.swing.JRadioButton();
        btnRelLimpar = new javax.swing.JButton();
        btnRelPesq = new javax.swing.JButton();
        btnRelMudar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Controle de Gastos");
        setPreferredSize(new java.awt.Dimension(755, 590));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cboMesCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));

        jLabel3.setText("Mês");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        jLabel2.setText("Valor");

        jLabel1.setText("Descrição do Gasto");

        buttonGroup1.add(rbtMensal);
        rbtMensal.setText("Mensal");
        rbtMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMensalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtFixo);
        rbtFixo.setText("Fixo");
        rbtFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFixoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtMensal)
                        .addGap(35, 35, 35)
                        .addComponent(rbtFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMesCadastro, 0, 140, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMesCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMensal)
                    .addComponent(rbtFixo))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        tblDespesa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblDespesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Desp", "Descrição", "Valor"
            }
        ));
        tblDespesa.setFocusable(false);
        tblDespesa.getTableHeader().setReorderingAllowed(false);
        tblDespesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDespesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDespesa);

        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });

        jLabel4.setText("Pesquisa");

        cboMesPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));
        cboMesPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMesPesqMouseClicked(evt);
            }
        });
        cboMesPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesPesqActionPerformed(evt);
            }
        });
        cboMesPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMesPesqKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboMesPesqKeyReleased(evt);
            }
        });

        jLabel5.setText("Mês");

        btnPagar.setText("Pagar");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnSubtotal.setText("Subtotal");
        btnSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMesPesq, 0, 140, Short.MAX_VALUE)
                    .addComponent(txtSubtotal)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMesPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/delete.png"))); // NOI18N
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/create.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/update.png"))); // NOI18N
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/Vassoura.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/read.png"))); // NOI18N
        btnPesquisar.setEnabled(false);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Despesas", jPanel2);

        tblRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRelatorioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRelatorio);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculo das Despesas"));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 148));

        btnRelCalcular.setText("Calcular");
        btnRelCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelCalcularActionPerformed(evt);
            }
        });

        jLabel7.setText("Despesas Pagas");

        jLabel8.setText("Despesas Pendentes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnRelCalcular)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDespPagas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtDespPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnRelCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDespPagas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtDespPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa por Tipo de Despesa"));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 147));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 160));

        buttonGroup2.add(rbtRelAmbas);
        rbtRelAmbas.setText("Ambas");
        rbtRelAmbas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRelAmbasActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtRelPendente);
        rbtRelPendente.setText("Pendentes");
        rbtRelPendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRelPendenteActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtRelPaga);
        rbtRelPaga.setText("Pagas");
        rbtRelPaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRelPagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtRelPaga)
                    .addComponent(rbtRelAmbas)
                    .addComponent(rbtRelPendente))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtRelAmbas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtRelPendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtRelPaga)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(160, 160));

        buttonGroup3.add(rbtRelMensal);
        rbtRelMensal.setText("Mensal");
        rbtRelMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRelMensalActionPerformed(evt);
            }
        });

        cboRelMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));

        buttonGroup3.add(rbtRelTodas);
        rbtRelTodas.setText("Todas");
        rbtRelTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtRelTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtRelTodas)
                            .addComponent(rbtRelMensal)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(cboRelMes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtRelTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtRelMensal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboRelMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRelLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/Vassoura.png"))); // NOI18N
        btnRelLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelLimparActionPerformed(evt);
            }
        });

        btnRelPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/read.png"))); // NOI18N
        btnRelPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPesqActionPerformed(evt);
            }
        });

        btnRelMudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/update.png"))); // NOI18N
        btnRelMudar.setEnabled(false);
        btnRelMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelMudarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnRelPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelMudar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelMudar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatórios", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setBounds(0, 0, 755, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        adicionar();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        // TODO add your handling code here:
        pesquisarDespesa();
    }//GEN-LAST:event_txtPesqKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        setarCampos();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rbtMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMensalActionPerformed
        // TODO add your handling code here:
        tipo = "Mesal";
    }//GEN-LAST:event_rbtMensalActionPerformed

    private void rbtFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFixoActionPerformed
        // TODO add your handling code here:
        tipo = "Fixo";
    }//GEN-LAST:event_rbtFixoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        rbtMensal.setSelected(true);
        tipo = "Mensal";

        rbtRelTodas.setSelected(true);
        periodo = "TODAS";
        cboRelMes.setEnabled(false);
        cboRelMes.setSelectedItem(" ");

        rbtRelAmbas.setSelected(true);
        tipoPeriodo = "AMBAS";
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        pagarDespesa();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void tblDespesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDespesaMouseClicked
        // TODO add your handling code here:
        btnPesquisar.setEnabled(true);
        btnPagar.setEnabled(true);
    }//GEN-LAST:event_tblDespesaMouseClicked

    private void btnRelCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelCalcularActionPerformed
        // TODO add your handling code here:
        pesquisaSomaRelatorio();

    }//GEN-LAST:event_btnRelCalcularActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        excliurDespesa();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        editarDespesa();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void rbtRelTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRelTodasActionPerformed
        // TODO add your handling code here:
        periodo = "TODAS";
        cboRelMes.setEnabled(false);
        cboRelMes.setSelectedItem(" ");

    }//GEN-LAST:event_rbtRelTodasActionPerformed

    private void rbtRelMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRelMensalActionPerformed
        // TODO add your handling code here:
        periodo = "MENSAL";
        cboRelMes.setEnabled(true);

    }//GEN-LAST:event_rbtRelMensalActionPerformed

    private void rbtRelAmbasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRelAmbasActionPerformed
        // TODO add your handling code here:
        tipoPeriodo = "AMBAS";
    }//GEN-LAST:event_rbtRelAmbasActionPerformed

    private void rbtRelPendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRelPendenteActionPerformed
        // TODO add your handling code here:
        tipoPeriodo = "PENDENTE";
    }//GEN-LAST:event_rbtRelPendenteActionPerformed

    private void rbtRelPagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtRelPagaActionPerformed
        // TODO add your handling code here:
        tipoPeriodo = "PAGO";
    }//GEN-LAST:event_rbtRelPagaActionPerformed

    private void btnRelPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPesqActionPerformed
        // TODO add your handling code here:
        if (periodo.equals("TODAS")) {
            if (tipoPeriodo.equals("AMBAS")) {
                pesquisaComFiltro1();

            } else {
                pesquisaComFiltro2();

            }
        } else {
            if (tipoPeriodo.equals("AMBAS")) {
                pesquisaComFiltro3();

            } else {
                pesquisaComFiltro4();

            }

        }
        txtDespPagas.setText(null);
        txtDespPendentes.setText(null);
    }//GEN-LAST:event_btnRelPesqActionPerformed

    private void btnRelMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelMudarActionPerformed
        // TODO add your handling code here:
        editarDespesaPaga();
    }//GEN-LAST:event_btnRelMudarActionPerformed

    private void tblRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelatorioMouseClicked
        // TODO add your handling code here:
        btnRelMudar.setEnabled(true);
    }//GEN-LAST:event_tblRelatorioMouseClicked

    private void btnRelLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelLimparActionPerformed
        // TODO add your handling code here:
        limparRelatorio();
    }//GEN-LAST:event_btnRelLimparActionPerformed

    private void cboMesPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesPesqActionPerformed
        // TODO add your handling code here:
        pesquisarMes();
    }//GEN-LAST:event_cboMesPesqActionPerformed

    private void cboMesPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMesPesqKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMesPesqKeyReleased

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void cboMesPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMesPesqMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMesPesqMouseClicked

    private void cboMesPesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMesPesqKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboMesPesqKeyPressed

    private void btnSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtotalActionPerformed
        // TODO add your handling code here:
        pesquisaSomaDespesa();
        txtPesq.setText(null);
    }//GEN-LAST:event_btnSubtotalActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        String caracteres = "0123456789,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRelCalcular;
    private javax.swing.JButton btnRelLimpar;
    private javax.swing.JButton btnRelMudar;
    private javax.swing.JButton btnRelPesq;
    private javax.swing.JButton btnSubtotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboMesCadastro;
    private javax.swing.JComboBox<String> cboMesPesq;
    private javax.swing.JComboBox<String> cboRelMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtFixo;
    private javax.swing.JRadioButton rbtMensal;
    private javax.swing.JRadioButton rbtRelAmbas;
    private javax.swing.JRadioButton rbtRelMensal;
    private javax.swing.JRadioButton rbtRelPaga;
    private javax.swing.JRadioButton rbtRelPendente;
    private javax.swing.JRadioButton rbtRelTodas;
    private javax.swing.JTable tblDespesa;
    private javax.swing.JTable tblRelatorio;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDespPagas;
    private javax.swing.JTextField txtDespPendentes;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void setarCampos() {
        int setar = tblDespesa.getSelectedRow();
        String setado = tblDespesa.getModel().getValueAt(setar, 0).toString();

        String sql = "select * from tb_despesas where id_desp = ?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, setado);

            rs = pst.executeQuery();

            if (rs.next()) {

                txtDescricao.setText(rs.getString(2));
                txtValor.setText(rs.getString(3));
                cboMesCadastro.setSelectedItem(rs.getString(5));
                

                String tiporbt = rs.getString(4);
                if (tiporbt.equals("Mensal")) {
                    rbtMensal.setSelected(true);
                    tipo = "Mensal";
                } else {
                    rbtFixo.setSelected(true);
                    tipo = "Fixo";
                }
                btnPagar.setEnabled(false);
                btnPesquisar.setEnabled(false);
                btnAdicionar.setEnabled(false);
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void adicionar() {

        String sql = "insert into tb_despesas(descricao_desp, valor, tipo_desp, mes_ref, situacao)"
                + "values(?, ?, ?, ?, ?)";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtDescricao.getText());
            pst.setString(2, txtValor.getText().replace(",", "."));
            pst.setString(3, tipo);
            pst.setString(4, cboMesCadastro.getSelectedItem().toString());
            pst.setString(5, "PENDENTE");

            if (txtDescricao.getText().isEmpty() || txtValor.getText().isEmpty() || cboMesCadastro.getSelectedItem().equals(" ")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");

            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Despesa adicionada com sucesso!");
                    limparCampos();
                    limparRelatorio();
                }

            }
            System.out.println(tipo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void limparCampos() {

        txtPesq.setText(null);
        cboMesPesq.setSelectedItem(" ");
        txtSubtotal.setText(null);
        txtDescricao.setText(null);
        txtValor.setText(null);
        cboMesCadastro.setSelectedItem(" ");

        btnPesquisar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        btnPagar.setEnabled(false);

        btnAdicionar.setEnabled(true);
        pesquisarDespesa();

    }

    private void limparRelatorio() {

        rbtRelTodas.setSelected(true);
        periodo = "TODAS";
        cboRelMes.setEnabled(false);
        cboRelMes.setSelectedItem(" ");

        rbtRelAmbas.setSelected(true);
        tipoPeriodo = "AMBAS";

        txtDespPagas.setText(null);
        txtDespPendentes.setText(null);

        btnRelMudar.setEnabled(false);
        pesquisaComFiltro1();

    }

    private void pagarDespesa() {

        int pagar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja marcar como PAGA está despesa?", "Atenção!!!", JOptionPane.YES_NO_OPTION);

        if (pagar == JOptionPane.YES_OPTION) {

            String sql = "update tb_despesas set situacao=? where id_desp=?";
            //int setar = tblTabela.getSelectedRow();
            //String setado = tblTabela.getModel().getValueAt(setar, 0).toString();

            String setado = tblDespesa.getModel().getValueAt(tblDespesa.getSelectedRow(), 0).toString();

            try {

                pst = conn.prepareStatement(sql);
                pst.setString(1, "PAGO");
                pst.setString(2, setado);

                int pago = pst.executeUpdate();

                if (pago > 0) {
                    JOptionPane.showMessageDialog(null, "Despesa PAGA");
                    pesquisarDespesa();
                    limparRelatorio();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }

    private void excliurDespesa() {

        int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir essa despesa?", "Atenção!!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {

            String sql = "delete from tb_despesas where id_desp=? ";

            try {
                pst = conn.prepareStatement(sql);
                String setado = tblDespesa.getModel().getValueAt(tblDespesa.getSelectedRow(), 0).toString();
                pst.setString(1, setado);
                int excluido = pst.executeUpdate();
                if (excluido > 0) {
                    JOptionPane.showMessageDialog(null, "Despesa excluída com sucesso!");
                    pesquisarDespesa();
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void editarDespesa() {

        String sql = "update tb_despesas set descricao_desp=?, valor=?, tipo_desp=?, mes_ref=?, situacao=? where id_desp=?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtDescricao.getText());
            pst.setString(2, txtValor.getText().replace(",", "."));
            pst.setString(3, tipo);
            pst.setString(4, cboMesCadastro.getSelectedItem().toString());
            pst.setString(5, "PENDENTE");
            String setado = tblDespesa.getModel().getValueAt(tblDespesa.getSelectedRow(), 0).toString();
            pst.setString(6, setado);

            if (txtDescricao.getText().isEmpty() || txtValor.getText().isEmpty() || cboMesCadastro.getSelectedItem().equals(" ")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");

            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Despesa modificada com sucesso!");
                    limparCampos();
                    limparRelatorio();
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void editarDespesaPaga() {

        String sql = "update tb_despesas set situacao=? where id_desp=?";
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja modificar a despesa de PAGA para PENDENTE?", "Atenção !!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {

            try {

                pst = conn.prepareStatement(sql);
                pst.setString(1, "PENDENTE");
                String setado = tblRelatorio.getModel().getValueAt(tblRelatorio.getSelectedRow(), 0).toString();
                pst.setString(2, setado);

                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Despesa modificada para PENDENTE!");
                    limparRelatorio();
                    limparCampos();

                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    private void pesquisarDespesa() {

        String sql = "select * from tb_despesas where situacao=? and descricao_desp like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "PENDENTE");
            pst.setString(2, "%" + txtPesq.getText() + "%");

            rs = pst.executeQuery();

            tblDespesa.setModel(DbUtils.resultSetToTableModel(rs));

            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnPagar.setEnabled(false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisarMes() {

        String sql = "select * from tb_despesas where situacao=? and mes_ref=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "PENDENTE");
            pst.setString(2, cboMesPesq.getSelectedItem().toString());

            rs = pst.executeQuery();

            tblDespesa.setModel(DbUtils.resultSetToTableModel(rs));
            txtSubtotal.setText(null);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnPagar.setEnabled(false);
            btnPesquisar.setEnabled(false);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaRelatorio() {

        String sql = "select * from tb_despesas where descricao_desp like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesq.getText() + "%");

            rs = pst.executeQuery();

            tblRelatorio.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaComFiltro1() {
        String sql = "select * from tb_despesas";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            tblRelatorio.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaComFiltro2() {
        String sql = "select * from tb_despesas where situacao=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tipoPeriodo);
            rs = pst.executeQuery();

            tblRelatorio.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaComFiltro3() {
        String sql = "select * from tb_despesas where mes_ref=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, cboRelMes.getSelectedItem().toString());
            if (cboRelMes.getSelectedItem().toString().equals(" ")) {
                JOptionPane.showMessageDialog(null, "Preencha o Mês desejado");
            } else {
                rs = pst.executeQuery();
            }

            tblRelatorio.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaComFiltro4() {
        String sql = "select * from tb_despesas where mes_ref=? and situacao=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, cboRelMes.getSelectedItem().toString());
            pst.setString(2, tipoPeriodo);

            if (cboRelMes.getSelectedItem().toString().equals(" ")) {
                JOptionPane.showMessageDialog(null, "Preencha o Mês desejado");
            } else {
                rs = pst.executeQuery();
            }

            tblRelatorio.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaSomaRelatorio() {
        int linhas = tblRelatorio.getRowCount();
        double somaPen = 0;
        double somaPg = 0;

        for (int i = 0; i < linhas; i++) {
            String sit = tblRelatorio.getValueAt(i, 5).toString();
            if (sit.equals("PENDENTE")) {
                somaPen += obj(tblRelatorio.getValueAt(i, 2));

            } else {
                somaPg += obj(tblRelatorio.getValueAt(i, 2));

            }

        }

        txtDespPendentes.setText(String.valueOf(somaPen));
        txtDespPagas.setText(String.valueOf(somaPg));

    }

    private void pesquisaSomaDespesa() {
        int linhas = tblDespesa.getRowCount();
        double soma = 0;

        for (int i = 0; i < linhas; i++) {
            soma += obj(tblDespesa.getValueAt(i, 2));
        }

        txtSubtotal.setText(String.valueOf(soma));
    }

//Função para pegar uma String e tranforma em Double
    public static double obj(Object obj) {
        String str = obj.toString();
        return Double.parseDouble(str);
    }

//Função para pegar uma String e tranforma em Double

}
