/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.wj.telas;

import br.com.wj.dal.ModuloConexao;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Geyvson
 */
public class TelaServicos extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tipo;
    String tipo2;
    String v;
    int comissao;
    DefaultTableModel meus_produtos;

    /**
     * Creates new form TelaServicos
     */
    public TelaServicos() {
        initComponents();
        conn = ModuloConexao.conectaBD();
        pesquisaServProd();
        pesquisaServicos();
        comboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlPainel_Guias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtServPesqProd = new javax.swing.JTextField();
        rbtServPesqDesc = new javax.swing.JRadioButton();
        rbtServPesqCod = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServPesqProd = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtServProd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtServServ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboServTec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtServQtdEstoque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtServValor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServCarrinho = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnAdicionarItem = new javax.swing.JButton();
        txtServIdTec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnRemoverItem = new javax.swing.JButton();
        txtIdServ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtServQtd = new javax.swing.JTextField();
        btnServAdicionar = new javax.swing.JButton();
        btnServExcluir = new javax.swing.JButton();
        btnServLimpar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPesqServRealizados = new javax.swing.JTextField();
        rbtServReaDesc = new javax.swing.JRadioButton();
        rbtServReaCod = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServRealizados = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnServPesq = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquisa de Produto");

        txtServPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServPesqProdKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbtServPesqDesc);
        rbtServPesqDesc.setText("Descrição");
        rbtServPesqDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtServPesqDescActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtServPesqCod);
        rbtServPesqCod.setText("Código");
        rbtServPesqCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtServPesqCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbtServPesqDesc)
                .addGap(31, 31, 31)
                .addComponent(rbtServPesqCod)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtServPesqProd)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtServPesqCod)
                    .addComponent(rbtServPesqDesc))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblServPesqProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblServPesqProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServPesqProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServPesqProd);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Produto");

        txtServProd.setEnabled(false);

        jLabel3.setText("Serviço");

        txtServServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServServKeyReleased(evt);
            }
        });

        jLabel4.setText("Técnico");

        cboServTec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        cboServTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboServTecActionPerformed(evt);
            }
        });
        cboServTec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboServTecKeyReleased(evt);
            }
        });

        jLabel5.setText("Estoque");

        txtServQtdEstoque.setEnabled(false);

        jLabel6.setText("Valor");

        txtServValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServValorActionPerformed(evt);
            }
        });
        txtServValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServValorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtServValorKeyTyped(evt);
            }
        });

        tblServCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Qtd"
            }
        ));
        tblServCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServCarrinhoMouseClicked(evt);
            }
        });
        tblServCarrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblServCarrinhoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblServCarrinho);

        jLabel8.setText("QTD");

        btnAdicionarItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdicionarItem.setText("+");
        btnAdicionarItem.setToolTipText("Adicionar ao Carrinho");
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        txtServIdTec.setEnabled(false);
        txtServIdTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServIdTecActionPerformed(evt);
            }
        });

        jLabel9.setText("Id do Técnico");

        btnRemoverItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemoverItem.setText("-");
        btnRemoverItem.setToolTipText("Adicionar ao Carrinho");
        btnRemoverItem.setEnabled(false);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        txtIdServ.setEnabled(false);

        jLabel10.setText("Serviço Nº");

        txtServQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServQtdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboServTec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServIdTec, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtServProd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtServQtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtServQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtServServ, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtServValor)))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdServ)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtServQtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(txtServQtd)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServServ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboServTec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServIdTec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdServ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnServAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/create.png"))); // NOI18N
        btnServAdicionar.setEnabled(false);
        btnServAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServAdicionarActionPerformed(evt);
            }
        });

        btnServExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/delete.png"))); // NOI18N
        btnServExcluir.setEnabled(false);
        btnServExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServExcluirActionPerformed(evt);
            }
        });

        btnServLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/Vassoura.png"))); // NOI18N
        btnServLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnServAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnServExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnServLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnServLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlPainel_Guias.addTab("Inserir Serviços", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(246, 136));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pesquisa de Serviço");

        txtPesqServRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqServRealizadosActionPerformed(evt);
            }
        });
        txtPesqServRealizados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqServRealizadosKeyReleased(evt);
            }
        });

        buttonGroup2.add(rbtServReaDesc);
        rbtServReaDesc.setText("Descrição");
        rbtServReaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtServReaDescActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtServReaCod);
        rbtServReaCod.setText("Código");
        rbtServReaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtServReaCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbtServReaDesc)
                .addGap(31, 31, 31)
                .addComponent(rbtServReaCod)
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPesqServRealizados)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesqServRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtServReaCod)
                    .addComponent(rbtServReaDesc))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tblServRealizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblServRealizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServRealizadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblServRealizados);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnServPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/read.png"))); // NOI18N
        btnServPesq.setEnabled(false);
        btnServPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnServPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnServPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlPainel_Guias.addTab("Serviços Realizados", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPainel_Guias, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPainel_Guias)
                .addContainerGap())
        );

        setBounds(0, 0, 755, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void txtServPesqProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServPesqProdKeyReleased
        // TODO add your handling code here:
        if (tipo.equals("descricao")) {
            pesquisaServProd();
        } else {
            pesquisaServProdCod();
        }
    }//GEN-LAST:event_txtServPesqProdKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        rbtServPesqDesc.setSelected(true);
        tipo = "descricao";

        rbtServReaDesc.setSelected(true);
        tipo2 = "descricao";
    }//GEN-LAST:event_formInternalFrameOpened

    private void rbtServPesqDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtServPesqDescActionPerformed
        // TODO add your handling code here:
        tipo = "descricao";
    }//GEN-LAST:event_rbtServPesqDescActionPerformed

    private void rbtServPesqCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtServPesqCodActionPerformed
        // TODO add your handling code here:
        tipo = "codigo";
    }//GEN-LAST:event_rbtServPesqCodActionPerformed

    private void tblServPesqProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServPesqProdMouseClicked
        // TODO add your handling code here:
        setar();
    }//GEN-LAST:event_tblServPesqProdMouseClicked

    private void txtPesqServRealizadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqServRealizadosKeyReleased
        // TODO add your handling code here:
        if (tipo2.equals("descricao")) {
            pesquisaServicos();
        } else {
            pesquisaServicosCod();
        }
        btnServPesq.setEnabled(false);

    }//GEN-LAST:event_txtPesqServRealizadosKeyReleased

    private void rbtServReaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtServReaDescActionPerformed
        // TODO add your handling code here:
        tipo2 = "descricao";
    }//GEN-LAST:event_rbtServReaDescActionPerformed

    private void rbtServReaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtServReaCodActionPerformed
        // TODO add your handling code here:
        tipo2 = "codigo";
    }//GEN-LAST:event_rbtServReaCodActionPerformed

    private void tblServCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServCarrinhoMouseClicked
        // TODO add your handling code here:
        btnRemoverItem.setEnabled(true);
    }//GEN-LAST:event_tblServCarrinhoMouseClicked

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        // TODO add your handling code here:
        inserirNoCarrinho();
        ativarBotao();
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void cboServTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboServTecActionPerformed
        // TODO add your handling code here:
        setarId();
        ativarBotao();
    }//GEN-LAST:event_cboServTecActionPerformed

    private void btnServAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServAdicionarActionPerformed
        // TODO add your handling code here:
        salvarServico();
    }//GEN-LAST:event_btnServAdicionarActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        // TODO add your handling code here:
        excluirDoCarrinho();
        ativarBotao();
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnServLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnServLimparActionPerformed

    private void txtServServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServServKeyReleased
        // TODO add your handling code here:
        ativarBotao();
    }//GEN-LAST:event_txtServServKeyReleased

    private void txtServValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServValorKeyReleased
        // TODO add your handling code here:

        v = tiraVirgula(txtServValor.getText());
        ativarBotao();
    }//GEN-LAST:event_txtServValorKeyReleased

    private void cboServTecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboServTecKeyReleased
        // TODO add your handling code here:
        ativarBotao();
    }//GEN-LAST:event_cboServTecKeyReleased

    private void tblServCarrinhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServCarrinhoKeyReleased
        // TODO add your handling code here:
        ativarBotao();
    }//GEN-LAST:event_tblServCarrinhoKeyReleased

    private void btnServPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServPesqActionPerformed
        // TODO add your handling code here:
        setarServico();
        btnServPesq.setEnabled(false);
    }//GEN-LAST:event_btnServPesqActionPerformed

    private void tblServRealizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServRealizadosMouseClicked
        // TODO add your handling code here:
        btnServPesq.setEnabled(true);
    }//GEN-LAST:event_tblServRealizadosMouseClicked

    private void txtPesqServRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqServRealizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqServRealizadosActionPerformed

    private void btnServExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServExcluirActionPerformed
        // TODO add your handling code here:
        exclusaoCompleta();
    }//GEN-LAST:event_btnServExcluirActionPerformed

    private void txtServQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServQtdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServQtdKeyReleased

    private void txtServValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServValorActionPerformed

    private void txtServIdTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServIdTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServIdTecActionPerformed

    private void txtServValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServValorKeyTyped
        // Action Key Typed
        String caracteres = "0123456789,";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtServValorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnServAdicionar;
    private javax.swing.JButton btnServExcluir;
    private javax.swing.JButton btnServLimpar;
    private javax.swing.JButton btnServPesq;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboServTec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane pnlPainel_Guias;
    private javax.swing.JRadioButton rbtServPesqCod;
    private javax.swing.JRadioButton rbtServPesqDesc;
    private javax.swing.JRadioButton rbtServReaCod;
    private javax.swing.JRadioButton rbtServReaDesc;
    private javax.swing.JTable tblServCarrinho;
    private javax.swing.JTable tblServPesqProd;
    private javax.swing.JTable tblServRealizados;
    private javax.swing.JTextField txtIdServ;
    private javax.swing.JTextField txtPesqServRealizados;
    private javax.swing.JTextField txtServIdTec;
    private javax.swing.JTextField txtServPesqProd;
    private javax.swing.JTextField txtServProd;
    private javax.swing.JTextField txtServQtd;
    private javax.swing.JTextField txtServQtdEstoque;
    private javax.swing.JTextField txtServServ;
    private javax.swing.JTextField txtServValor;
    // End of variables declaration//GEN-END:variables

    private void pesquisaServProd() {

        String sql = "select * from tb_produtos where descricao_prod like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtServPesqProd.getText() + "%");

            rs = pst.executeQuery();

            tblServPesqProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaServProdCod() {

        String sql = "select * from tb_produtos where id_prod like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtServPesqProd.getText() + "%");

            rs = pst.executeQuery();

            tblServPesqProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void setar() {
        int setar = tblServPesqProd.getSelectedRow();

        txtServProd.setText(tblServPesqProd.getModel().getValueAt(setar, 1).toString());
        txtServQtdEstoque.setText(tblServPesqProd.getModel().getValueAt(setar, 2).toString());
        txtServQtd.setEnabled(true);
        txtServQtd.setText("1");
        btnAdicionarItem.setEnabled(true);

    }

    private void pesquisaServicos() {

        String sql = "select * from tb_servicos where descricao_serv like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesqServRealizados.getText() + "%");

            rs = pst.executeQuery();

            tblServRealizados.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void pesquisaServicosCod() {

        String sql = "select * from tb_servicos where id_serv like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesqServRealizados.getText() + "%");

            rs = pst.executeQuery();

            tblServRealizados.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void inserirNoCarrinho() {

        String id = tblServPesqProd.getModel().getValueAt(tblServPesqProd.getSelectedRow(), 0).toString();

        if (!txtServProd.getText().isEmpty()) {
            String est = txtServQtdEstoque.getText();
            String qt = txtServQtd.getText();
            int estoque = Integer.parseInt(est);
            int qtd = Integer.parseInt(qt);
            if (estoque >= qtd) {
                meus_produtos = (DefaultTableModel) tblServCarrinho.getModel();
                meus_produtos.addRow(new Object[]{
                    id,
                    txtServProd.getText(),
                    txtServQtd.getText()
                });
                txtServProd.setText(null);
                txtServQtdEstoque.setText(null);
                txtServQtd.setText(null);
                btnAdicionarItem.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Quantidada Maior que o Estoque!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os Campos!");
        }

    }

    private void excluirDoCarrinho() {

        meus_produtos = (DefaultTableModel) tblServCarrinho.getModel();
        meus_produtos.removeRow(tblServCarrinho.getSelectedRow());
        btnRemoverItem.setEnabled(false);

    }

    private int retornaUltimoIdServico() {
        int ultimoId = 0;
        String sql = "select max(id_serv) id_serv from tb_servicos";

        try {

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                ultimoId = rs.getInt("id_serv");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ultimoId;

    }

    private int retornaQtdEstoque(int id) {
        int quant = 0;
        String sql = "select * from tb_produtos where id_prod=?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);

            rs = pst.executeQuery();

            if (rs.next()) {
                quant = rs.getInt("qtd_atual");
                return quant;

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao retornar a quantidade");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERRO" + e);

        }
        return quant;
    }

    private void salvarServico() {
        double v1 = Double.parseDouble(v);
        double valorComissao = v1 * comissao / 100;
        int idRetorno;
        int estoque;

        String sql = "insert into tb_servicos(descricao_serv, valor, comissao, id_user) values(?, ?, ?, ?)";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtServServ.getText());
            pst.setDouble(2, Double.parseDouble(v));
            pst.setDouble(3, valorComissao);
            pst.setString(4, txtServIdTec.getText());

            int adicionado = pst.executeUpdate();

            if (adicionado > 0) {
                JOptionPane.showMessageDialog(null, "Serviço Inserido com Sucesso!!!");

                inserirDespesaDiretamete();

                for (int i = 0; i < tblServCarrinho.getRowCount(); i++) {
                    idRetorno = retornaUltimoIdServico();
                    int idProd = Integer.parseInt(tblServCarrinho.getValueAt(i, 0).toString());
                    int qtdComprada = Integer.parseInt(tblServCarrinho.getValueAt(i, 2).toString());
                    estoque = retornaQtdEstoque(idProd);
                    int qtdAtualizada = estoque - qtdComprada;

                    salvarItens(idRetorno, idProd, qtdComprada);
                    baixaEstoque(qtdAtualizada, idProd);
                    pesquisaServProd();
                }

                pesquisaServicos();
                limparCampos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void devolverEstoque(int qtdTotal, int idRepor) {
        String sql = "update tb_produtos set qtd_atual=? where id_prod=?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setInt(1, qtdTotal);
            pst.setInt(2, idRepor);

            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void salvarItens(int idSv, int idP, int qtd) {
        String sql = "insert into tb_itens_servicos (id_serv, id_prod, qtd) values(?, ?, ?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, idSv);
            pst.setInt(2, idP);
            pst.setInt(3, qtd);

            pst.execute();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void baixaEstoque(int qtdAtualizada, int id) {

        String sql = "update tb_produtos set qtd_atual=? where id_prod=?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setInt(1, qtdAtualizada);
            pst.setInt(2, id);

            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void comboBox() {
        String sql = "select * from tb_usuarios";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cboServTec.addItem(rs.getString("usuario"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarId() {
        String sql = "Select * from tb_usuarios where usuario=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, cboServTec.getSelectedItem().toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtServIdTec.setText(rs.getString("id_user"));
                comissao = rs.getInt("comissao");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarNome() {
        String sql = "Select * from tb_usuarios where id_user=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 5).toString());
            rs = pst.executeQuery();
            if (rs.next()) {
                cboServTec.setSelectedItem(rs.getString("usuario"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void limparCampos() {
        for (int b = tblServCarrinho.getRowCount(); b > 0; b--) {
            meus_produtos = (DefaultTableModel) tblServCarrinho.getModel();
            meus_produtos.removeRow(0);

        }

        txtServPesqProd.setText(null);
        txtServProd.setText(null);
        txtServQtdEstoque.setText(null);
        txtServQtd.setText(null);
        btnAdicionarItem.setEnabled(false);
        txtServServ.setText(null);
        txtServValor.setText(null);
        cboServTec.setSelectedItem(" ");
        txtServIdTec.setText(null);
        txtIdServ.setText(null);

        btnRemoverItem.setEnabled(false);
        btnServExcluir.setEnabled(false);

        pesquisaServProd();

    }

    private void ativarBotao() {
        if (txtServServ.getText().isEmpty() || txtServValor.getText().isEmpty() || cboServTec.getSelectedItem().equals(" ")
                || !txtIdServ.getText().isEmpty() || (tblServCarrinho.getRowCount() == 0)) {
            btnServAdicionar.setEnabled(false);

        } else {
            btnServAdicionar.setEnabled(true);
        }
    }

    private void setarServico() {
        pnlPainel_Guias.setSelectedIndex(0);

        txtIdServ.setText(tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 0).toString());
        //cboServTec.
        txtServServ.setText(tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 2).toString());
        txtServValor.setText(tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 3).toString());
        txtServIdTec.setText(tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 5).toString());
        setarNome();

        String sql = "select i.id_prod as Produto, p.descricao_prod as Descrição ,i.qtd as Qtd from tb_itens_servicos as i inner join tb_produtos as p on i.id_prod = p.id_prod where id_serv=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tblServRealizados.getValueAt(tblServRealizados.getSelectedRow(), 0).toString());

            rs = pst.executeQuery();
            tblServCarrinho.setModel(DbUtils.resultSetToTableModel(rs));
            //tblServCarrinho.setModel(DbUtils.resultSetToTableModel(rs));
            btnServExcluir.setEnabled(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void excluirServico(int id_prod) {

        String sql = "delete from tb_servicos where id_serv=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id_prod);
            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void excluirItens(int id_prod) {

        String sql = "delete from tb_itens_servicos where id_serv=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id_prod);
            pst.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private String verificaDespesa(int id_serv) {
        String sit = null;
        String sql = "select * from tb_despesas where id_serv=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id_serv);
            rs = pst.executeQuery();

            if (rs.next()) {
                sit = rs.getString("situacao");
            }
            return sit;

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }

    private void excluirDespesa(int id_serv) {

        String sql = "delete from tb_despesas where id_serv=? ";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id_serv);
            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void exclusaoCompleta() {
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja EXCLUIR ESTE SERVIÇO?", "Atenção !!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {

            int id = Integer.parseInt(txtIdServ.getText());
            String teste = verificaDespesa(id);

            excluirItens(id);
            excluirServico(id);

            if (teste.equals("PAGO")) {
                int confirmDespesa = JOptionPane.showConfirmDialog(null, "A comissão já está Paga, Deseja excluir a despesa asimm mesmo?", "Exclusão de Despesa", JOptionPane.YES_OPTION);
                if (confirmDespesa == JOptionPane.YES_OPTION) {
                    excluirDespesa(id);
                } else {
                    JOptionPane.showMessageDialog(null, "A despesa referente a comissão não será removida.");
                }
            } else {
                excluirDespesa(id);
            }

            for (int i = 0; i < tblServCarrinho.getRowCount(); i++) {

                int idRepor = Integer.parseInt(tblServCarrinho.getValueAt(i, 0).toString());
                int qtd = Integer.parseInt(tblServCarrinho.getValueAt(i, 2).toString());
                int estoque = retornaQtdEstoque(idRepor);
                int qtdTotal = estoque + qtd;

                devolverEstoque(qtdTotal, idRepor);
            }

            pesquisaServProd();
            pesquisaServicos();
            limparCampos();
        }
    }

    private void inserirDespesaDiretamete() {

        String nome = cboServTec.getSelectedItem().toString();
        double v1 = Double.parseDouble(v);
        double valorComissao = v1 * comissao / 100;
        int idRetorno = retornaUltimoIdServico();

        String sql = "insert into tb_despesas(descricao_desp, valor, tipo_desp, mes_ref, situacao, id_serv)"
                + "values(?, ?, ?, ?, ?, ?)";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, nome);
            pst.setDouble(2, valorComissao);
            pst.setString(3, "Comissao");
            pst.setString(4, retornaMes());
            pst.setString(5, "PENDENTE");
            pst.setInt(6, idRetorno);

            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private String retornaMes() {

        Date hoje = new Date();
        SimpleDateFormat dt = new SimpleDateFormat("MM");
        String a = dt.format(hoje);
        String mes = null;
        switch (a) {
            case "01" ->
                mes = "Jan";
            case "02" ->
                mes = "Fev";
            case "03" ->
                mes = "Mar";
            case "04" ->
                mes = "Abr";
            case "05" ->
                mes = "Mai";
            case "06" ->
                mes = "Jun";
            case "07" ->
                mes = "Jul";
            case "08" ->
                mes = "Ago";
            case "09" ->
                mes = "Set";
            case "10" ->
                mes = "Out";
            case "11" ->
                mes = "Nov";
            case "12" ->
                mes = "Dez";

        }
        return mes;
    }

    private String tiraVirgula(String numComVirg) {
        String semvirgula = new String();
        int t = numComVirg.length();

        for (int i = 0; i < t; i++) {
            if (numComVirg.charAt(i) == ',') {
                semvirgula += '.';
            } else {
                semvirgula += numComVirg.charAt(i);
            }
        }

        return semvirgula;
    }

}
