/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.wj.telas;

import br.com.wj.dal.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Geyvson
 */
public class TelaProduto extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private String tipo;

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        conn = ModuloConexao.conectaBD();
        pesquisarTabelaProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaPesquisaProd = new javax.swing.JTable();
        btnProdAdicionar = new javax.swing.JButton();
        btnProdLimpar = new javax.swing.JButton();
        btnProdEditar = new javax.swing.JButton();
        btnProdExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtQtdAtual = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQtdAdicionar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtPesq = new javax.swing.JTextField();
        rbtDesc = new javax.swing.JRadioButton();
        rbtCod = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Produtos");
        setPreferredSize(new java.awt.Dimension(755, 590));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblTabelaPesquisaProd = new javax.swing.JTable(){
            public boolean isCellEditable(int  rowIndex, int colIndex){
                return false;
            }

        };
        tblTabelaPesquisaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Fone"
            }
        ));
        tblTabelaPesquisaProd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblTabelaPesquisaProd.setFocusable(false);
        tblTabelaPesquisaProd.getTableHeader().setReorderingAllowed(false);
        tblTabelaPesquisaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabelaPesquisaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTabelaPesquisaProd);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnProdAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/create.png"))); // NOI18N
        btnProdAdicionar.setToolTipText("Inserir um produto");
        btnProdAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdAdicionarActionPerformed(evt);
            }
        });

        btnProdLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/Vassoura.png"))); // NOI18N
        btnProdLimpar.setToolTipText("Limpar todos os Campos");
        btnProdLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdLimparActionPerformed(evt);
            }
        });

        btnProdEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/update.png"))); // NOI18N
        btnProdEditar.setToolTipText("Editar o produto e adiociona quantidade");
        btnProdEditar.setEnabled(false);
        btnProdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdEditarActionPerformed(evt);
            }
        });

        btnProdExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wj/icones/delete.png"))); // NOI18N
        btnProdExcluir.setToolTipText("Excluir");
        btnProdExcluir.setEnabled(false);
        btnProdExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdExcluirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtQtdAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQtdAtual.setEnabled(false);

        txtCod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Código do Produto");

        jLabel7.setText("Quantidade Atual");

        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setText("Descrição");

        jLabel8.setText("Adicionar");

        txtQtdAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE))
                    .addComponent(txtDesc)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtdAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtQtdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbtDesc);
        rbtDesc.setText("Descrição");
        rbtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDescActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtCod);
        rbtCod.setText("Código");
        rbtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCodActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquisa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesq)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbtDesc)
                .addGap(30, 30, 30)
                .addComponent(rbtCod)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(txtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtDesc)
                    .addComponent(rbtCod))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnProdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnProdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnProdLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProdExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnProdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProdLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        setBounds(0, 0, 755, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTabelaPesquisaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabelaPesquisaProdMouseClicked
        // TODO add your handling code here:
        setarCampos();

    }//GEN-LAST:event_tblTabelaPesquisaProdMouseClicked

    private void btnProdAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdAdicionarActionPerformed
        // TODO add your handling code here:
        adicionar();

    }//GEN-LAST:event_btnProdAdicionarActionPerformed

    private void btnProdLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnProdLimparActionPerformed

    private void btnProdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdEditarActionPerformed
        // TODO add your handling code here:
        editarProd();
    }//GEN-LAST:event_btnProdEditarActionPerformed

    private void btnProdExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdExcluirActionPerformed
        // TODO add your handling code here:
        excluirProd();
    }//GEN-LAST:event_btnProdExcluirActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        // TODO add your handling code here:
        if (tipo.equals("descriçao")) {
            pesquisarTabelaProd();
        } else {
            pesquisarTabelaProdCod();
        }

    }//GEN-LAST:event_txtPesqKeyReleased

    private void rbtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDescActionPerformed
        // TODO add your handling code here:
        tipo = "descriçao";
    }//GEN-LAST:event_rbtDescActionPerformed

    private void rbtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCodActionPerformed
        // TODO add your handling code here:
        tipo = "codigo";
    }//GEN-LAST:event_rbtCodActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        rbtDesc.setSelected(true);
        tipo = "descriçao";
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProdAdicionar;
    private javax.swing.JButton btnProdEditar;
    private javax.swing.JButton btnProdExcluir;
    private javax.swing.JButton btnProdLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtCod;
    private javax.swing.JRadioButton rbtDesc;
    private javax.swing.JTable tblTabelaPesquisaProd;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtQtdAdicionar;
    private javax.swing.JTextField txtQtdAtual;
    // End of variables declaration//GEN-END:variables

    private void pesquisarTabelaProd() {
        String sql = "select id_prod as Código, descricao_prod as descrição, qtd_atual as Quantidade from tb_produtos where descricao_prod like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesq.getText() + "%");
            rs = pst.executeQuery();

            tblTabelaPesquisaProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisarTabelaProdCod() {
        String sql = "select id_prod as Código, descricao_prod as descrição, qtd_atual as Quantidade from tb_produtos where id_prod like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesq.getText() + "%");
            rs = pst.executeQuery();

            tblTabelaPesquisaProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void setarCampos() {
        int setar = tblTabelaPesquisaProd.getSelectedRow();

        txtCod.setText(tblTabelaPesquisaProd.getModel().getValueAt(setar, 0).toString());
        txtDesc.setText(tblTabelaPesquisaProd.getModel().getValueAt(setar, 1).toString());
        txtQtdAtual.setText(tblTabelaPesquisaProd.getModel().getValueAt(setar, 2).toString());

        btnProdAdicionar.setEnabled(false);
        btnProdEditar.setEnabled(true);
        btnProdExcluir.setEnabled(true);

    }

    private void adicionar() {

        String sql = "insert into tb_produtos(id_prod, descricao_prod, qtd_atual)"
                + "values(?,?,?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtCod.getText());
            pst.setString(2, txtDesc.getText());
            pst.setString(3, txtQtdAdicionar.getText());

            if (txtCod.getText().isEmpty() || txtDesc.getText().isEmpty() || txtQtdAdicionar.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatorios!!!");

            } else {

                int ad = pst.executeUpdate();

                if (ad > 0) {
                    JOptionPane.showMessageDialog(null, "Produto inserido com SUCESSO!!!");
                    limparCampos();
                    pesquisarTabelaProd();
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void limparCampos() {
        txtCod.setText(null);
        txtDesc.setText(null);
        txtPesq.setText(null);
        txtQtdAtual.setText(null);
        txtQtdAdicionar.setText(null);

        pesquisarTabelaProdCod();
        btnProdAdicionar.setEnabled(true);
        btnProdEditar.setEnabled(false);
        btnProdExcluir.setEnabled(false);

    }

    private void excluirProd() {

        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja EXCLUIR esté produto?", "Atenção !!!", JOptionPane.YES_NO_OPTION);

        if (confirma == JOptionPane.YES_OPTION) {
            String sql = "delete from tb_produtos where id_prod=?";

            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtCod.getText());
                int apagado = pst.executeUpdate();

                if (apagado > 0) {
                    JOptionPane.showMessageDialog(null, "Produto Excluído com sucesso!!");
                    limparCampos();
                    pesquisarTabelaProd();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }

    private void editarProd() {
        int soma, atual, adic;

        if (!txtQtdAdicionar.getText().isEmpty()) {
            atual = Integer.parseInt(txtQtdAtual.getText());
            adic = Integer.parseInt(txtQtdAdicionar.getText());
            soma = atual + adic;
        } else {
            soma = Integer.parseInt(txtQtdAtual.getText());
        }

        String sql = "update tb_produtos set descricao_prod=?, qtd_atual=? where id_prod=?";

        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txtDesc.getText());
            pst.setString(2, String.valueOf(soma));
            pst.setString(3, txtCod.getText());

            if (txtCod.getText().isEmpty() || txtDesc.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatorios!!!");

            } else {

                int ad = pst.executeUpdate();

                if (ad > 0) {
                    JOptionPane.showMessageDialog(null, "Produto alterado com SUCESSO!!!");
                    limparCampos();
                    pesquisarTabelaProd();
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
