/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.gugaLanches.telas;

import br.com.gugaLanches.dal.ModuloConexao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Geyvson
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaPagamento() {
        initComponents();
        conn = ModuloConexao.conectaDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtValorPedidoteste = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        btnRealizarPagamento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPix = new javax.swing.JTextField();
        txtDinheiro = new javax.swing.JTextField();
        txtCartao = new javax.swing.JTextField();
        txtSubTotal2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTroco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnColocarNaConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagamentos ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor do Pedido");

        txtValorPedidoteste.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorPedidoteste.setText("0");

        jLabel7.setText("Observação");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        btnRealizarPagamento.setText("PAGAR");
        btnRealizarPagamento.setEnabled(false);
        btnRealizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagamentoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Dinheiro");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Cartão");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Subtotal");

        txtPix.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPixKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPixKeyReleased(evt);
            }
        });

        txtDinheiro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDinheiroKeyReleased(evt);
            }
        });

        txtCartao.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCartaoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCartaoKeyReleased(evt);
            }
        });

        txtSubTotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubTotal2.setText("0");
        txtSubTotal2.setEnabled(false);
        txtSubTotal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSubTotal2KeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pix");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPix, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtTroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTroco.setText("0");
        txtTroco.setEnabled(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Troco");

        btnColocarNaConta.setText("Conta");
        btnColocarNaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColocarNaContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorPedidoteste))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRealizarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(btnColocarNaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtValorPedidoteste, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRealizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(btnColocarNaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(558, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void txtPixKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPixKeyReleased
        // TODO add your handling code here:
        subTotal();
        troco();
    }//GEN-LAST:event_txtPixKeyReleased

    private void txtDinheiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyReleased
        // TODO add your handling code here:
        subTotal();
        troco();
    }//GEN-LAST:event_txtDinheiroKeyReleased

    private void txtCartaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyReleased
        // TODO add your handling code here:
        subTotal();
        troco();
    }//GEN-LAST:event_txtCartaoKeyReleased

    private void txtPixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPixKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDinheiro.requestFocus();
        }
    }//GEN-LAST:event_txtPixKeyPressed

    private void txtDinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDinheiroKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCartao.requestFocus();
        }
    }//GEN-LAST:event_txtDinheiroKeyPressed

    private void txtCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaoKeyPressed

    private void txtSubTotal2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubTotal2KeyPressed
        // TODO add your handling code here:
//        pagar();
    }//GEN-LAST:event_txtSubTotal2KeyPressed

    private void btnColocarNaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColocarNaContaActionPerformed
        // TODO add your handling code here:
        pagamentoNaconta();
    }//GEN-LAST:event_btnColocarNaContaActionPerformed

    private void btnRealizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagamentoActionPerformed
        // TODO add your handling code here:
        pagar();
    }//GEN-LAST:event_btnRealizarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColocarNaConta;
    private javax.swing.JButton btnRealizarPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtPix;
    private javax.swing.JTextField txtSubTotal2;
    private javax.swing.JTextField txtTroco;
    public javax.swing.JTextField txtValorPedidoteste;
    // End of variables declaration//GEN-END:variables

    private void subTotal() {
        Double sub = 0.0;
        Double pix, din, cart;
        Double valorPedido = Double.valueOf(txtValorPedidoteste.getText());

        if (!txtPix.getText().isEmpty()) {
            pix = Double.valueOf(txtPix.getText());
        } else {
            pix = 0.0;
        }

        if (!txtDinheiro.getText().isEmpty()) {
            din = Double.valueOf(txtDinheiro.getText());
        } else {
            din = 0.0;
        }

        if (!txtCartao.getText().isEmpty()) {
            cart = Double.valueOf(txtCartao.getText());
        } else {
            cart = 0.0;
        }

        sub = pix + din + cart;

        txtSubTotal2.setText(sub.toString());
        if (sub >= valorPedido) {
            btnRealizarPagamento.setEnabled(true);
            btnColocarNaConta.setEnabled(false);
        } else {
            btnRealizarPagamento.setEnabled(false);
            btnColocarNaConta.setEnabled(true);
        }

    }

    private void pagar() {
        if (txtSubTotal2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os valores!!!");
        } else {

            Double subtotal = Double.valueOf(txtSubTotal2.getText());
            Double valorPedido = Double.valueOf(txtValorPedidoteste.getText());

            if (subtotal >= valorPedido) {

                String sql = "insert into tb_vendas(pix, dinheiro, cartao, conta, observacao) values(?, ?, ?, ?, ?)  ";

                try {
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, txtPix.getText());
                    pst.setString(2, txtDinheiro.getText());
                    pst.setString(3, txtCartao.getText());
                    pst.setString(4, "0");
                    pst.setString(5, txtObservacao.getText());

                    int adicionado = pst.executeUpdate();

                    if (adicionado > 0) {

                        JOptionPane.showMessageDialog(null, "Venda realizada!");
                        inserirItensDaVenda();

                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ");
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao Realizar a venda!");
                }

//                JOptionPane.showMessageDialog(null, "Pagamento Realizado \n Valor Pago: " + subtotal + "\n Total do Pedido:  " + valorPedido + "\nTroco: " + (subtotal - valorPedido));
            } else {
                JOptionPane.showMessageDialog(null, "Subtotal MENOR que o Valor do pedido!!!");
            }
        }

    }

    private void troco() {
        Double sub = Double.valueOf(txtSubTotal2.getText());
        Double valorPedido = Double.valueOf(txtValorPedidoteste.getText());
        Double troco;

        if (!txtSubTotal2.getText().isEmpty() && sub > 0) {
            if (sub > valorPedido) {
                troco = sub - valorPedido;
            } else {
                troco = 0.00;
            }
        } else {
            troco = 0.00;
        }

        txtTroco.setText(troco.toString());

    }

    private void pagamentoNaconta() {
        Double valor = Double.valueOf(txtValorPedidoteste.getText());
        Double subtotal = Double.valueOf(txtSubTotal2.getText());
        Double resto = valor - subtotal;

        telaColocarNaConta tela = new telaColocarNaConta();
        tela.txtValorDoDebito.setText(String.valueOf(resto));
        tela.setVisible(true);

    }

    private void finalizarPagamento() {

    }

    public void inserirItensDaVenda() {
        TelaVendasBalcao tela = new TelaVendasBalcao();
        int idRetorno;
        int estoque;
        for (int i = 0; i > tela.tblCarrinho.getRowCount(); i++) {
            idRetorno = retornaUltimoIdVenda();
            int codProd = Integer.parseInt(tela.tblCarrinho.getValueAt(i, 0).toString());
            int qtdComprada = Integer.parseInt(tela.tblCarrinho.getValueAt(i, 2).toString());
            Double preco = Double.valueOf(tela.tblCarrinho.getValueAt(i, 3).toString());
            Double valor = Double.valueOf(tela.tblCarrinho.getValueAt(i, 4).toString());
            estoque = retornaQtdEstoque(codProd);
            int qtdAtualizada = estoque - qtdComprada;

            salvarItens(idRetorno, codProd, qtdComprada, preco, valor);
            baixaEstoque(qtdAtualizada, codProd);
            tela.pesquisaServProd();

        }
    }

    public int retornaUltimoIdVenda() {

        int ultimoId = 0;

        String sql = "select max(id_venda) id_venda from tb_vendas";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                ultimoId = rs.getInt("id_venda");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ultimoId;

    }

    public int retornaQtdEstoque(int id) {
        int quant = 0;

        String sql = "select * from tb_produtos where cod_prod=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);

            rs = pst.executeQuery();
            if (rs.next()) {
                quant = rs.getInt("qtd_prod");
                return quant;
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao retornar a quantidade do Estoque!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return quant;
    }

    public void salvarItens(int idVenda, int codProd, int qtd, double preco, double valor) {
        String sql = "insert into tb_intens_da_venda(id_venda, cod_prod, qtd, preco, valor) values(?, ?, ?, ?, ?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, idVenda);
            pst.setInt(2, codProd);
            pst.setInt(3, qtd);
            pst.setDouble(4, preco);
            pst.setDouble(5, valor);

            pst.executeUpdate();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void baixaEstoque(int qtdAtualizada, int codProd) {
        String sql = "updete tb_produtos set qtd_prod=? where=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, qtdAtualizada);
            pst.setInt(2, codProd);

            pst.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

}
