/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.gugaLanches.telas;

/**
 *
 * @author Geyvson
 */
import br.com.gugaLanches.dal.ModuloConexao;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class TelaVendasBalcao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaVendas
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String tipo;
    DefaultTableModel meus_produtos;
    int qtdItens = 0;
    Double subTotal = 0.0;

    public TelaVendasBalcao() {
        initComponents();
        conn = ModuloConexao.conectaDb();
        pesquisaServProd();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnPagar = new javax.swing.JButton();
        btnServExcluir = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAdicionarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        txtQtd = new javax.swing.JTextField();
        btnCancelaItem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesqProd = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesqProd = new javax.swing.JTextField();
        rbtPesqProd = new javax.swing.JRadioButton();
        rbtPesqCod = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtQtdItens = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Vendas Balcão");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gugaLanches/icones/Money.png"))); // NOI18N
        btnPagar.setToolTipText("Pagar");
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnServExcluir.setToolTipText("");
        btnServExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServExcluirActionPerformed(evt);
            }
        });

        btnCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/gugaLanches/icones/Vassoura.png"))); // NOI18N
        btnCancelarPedido.setToolTipText("Cancelar Pedido");
        btnCancelarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Produto");

        txtProduto.setEnabled(false);

        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodKeyReleased(evt);
            }
        });

        jLabel5.setText("Código");

        txtPreco.setEnabled(false);

        jLabel6.setText("Valor");

        jLabel8.setText("QTD");

        btnAdicionarItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdicionarItem.setText("+");
        btnAdicionarItem.setToolTipText("Adicionar Item ao Pedido");
        btnAdicionarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemoverItem.setText("-");
        btnRemoverItem.setToolTipText("Remover Item do Pedido");
        btnRemoverItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoverItem.setEnabled(false);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdKeyReleased(evt);
            }
        });

        btnCancelaItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelaItem.setText("x");
        btnCancelaItem.setToolTipText("Cancelar Item");
        btnCancelaItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelaItem.setEnabled(false);
        btnCancelaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(407, 407, 407))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCancelaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblPesqProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPesqProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblPesqProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesqProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesqProd);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pesquisa de Produto");

        txtPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqProdKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbtPesqProd);
        rbtPesqProd.setText("Produto");
        rbtPesqProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPesqProdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtPesqCod);
        rbtPesqCod.setText("Código");
        rbtPesqCod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtPesqCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPesqCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rbtPesqProd)
                .addGap(31, 31, 31)
                .addComponent(rbtPesqCod)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPesqProd)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPesqCod)
                    .addComponent(rbtPesqProd))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Produto", "Qtd", "Preço", "Valor"
            }
        ));
        tblCarrinho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarrinhoMouseClicked(evt);
            }
        });
        tblCarrinho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCarrinhoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblCarrinho);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Quantidade de itens");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Subtotal");

        txtQtdItens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdItensKeyReleased(evt);
            }
        });

        txtSubtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubtotalKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnServExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7))
                            .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnServExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );

        setBounds(0, 0, 1133, 763);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        TelaPagamento tela = new TelaPagamento();
        String valor = txtSubtotal.getText();
        tela.txtValorPedidoteste.setText(valor);

        tela.setVisible(true);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnServExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServExcluirActionPerformed
        // TODO add your handling code here:
        inserirItensDaVenda();
    }//GEN-LAST:event_btnServExcluirActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
        cancelarPedido();

    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void txtCodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyReleased
        // TODO add your handling code here:
        ativarBotao();
    }//GEN-LAST:event_txtCodKeyReleased

    private void tblCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarrinhoMouseClicked
        // TODO add your handling code here:
        btnRemoverItem.setEnabled(true);
    }//GEN-LAST:event_tblCarrinhoMouseClicked

    private void tblCarrinhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCarrinhoKeyReleased
        // TODO add your handling code here:
        ativarBotao();
    }//GEN-LAST:event_tblCarrinhoKeyReleased

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        // TODO add your handling code here:
        inserirNoCarrinho();
        ativarBotao();
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        // TODO add your handling code here:
        excluirDoCarrinho();
        ativarBotao();
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void txtQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdKeyReleased

    private void tblPesqProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesqProdMouseClicked
        // TODO add your handling code here:
        setar();
        txtCod.setEnabled(false);
        txtQtd.requestFocus();
    }//GEN-LAST:event_tblPesqProdMouseClicked

    private void txtPesqProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqProdKeyReleased
        // TODO add your handling code here:
        if (tipo.equals("descricao")) {
            pesquisaServProd();
        } else {
            pesquisaServProdCod();
        }
    }//GEN-LAST:event_txtPesqProdKeyReleased

    private void rbtPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPesqProdActionPerformed
        // TODO add your handling code here:
        tipo = "descricao";
    }//GEN-LAST:event_rbtPesqProdActionPerformed

    private void rbtPesqCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPesqCodActionPerformed
        // TODO add your handling code here:
        tipo = "codigo";
    }//GEN-LAST:event_rbtPesqCodActionPerformed

    private void txtSubtotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubtotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalKeyReleased

    private void txtQtdItensKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdItensKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdItensKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        rbtPesqProd.setSelected(true);
        tipo = "descricao";
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCancelaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaItemActionPerformed
        // TODO add your handling code here:
        limpartextos();
    }//GEN-LAST:event_btnCancelaItemActionPerformed

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            inserirPorCodigo();
            ativarBotao();
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            inserirNoCarrinho();
            ativarBotao();
        }
    }//GEN-LAST:event_txtQtdKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnCancelaItem;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnServExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtPesqCod;
    private javax.swing.JRadioButton rbtPesqProd;
    public javax.swing.JTable tblCarrinho;
    private javax.swing.JTable tblPesqProd;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtPesqProd;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtQtdItens;
    public javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables

    public void pesquisaServProd() {
        String sql = "select * from tb_produtos where produto like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesqProd.getText() + "%");

            rs = pst.executeQuery();

            tblPesqProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisaServProdCod() {
        String sql = "select * from tb_produtos where cod_prod like ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + txtPesqProd.getText() + "%");

            rs = pst.executeQuery();

            tblPesqProd.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void inserirPorCodigo() {
        String sql = "select * from tb_produtos where cod_prod = ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtCod.getText());

            rs = pst.executeQuery();

            if (rs.next()) {
                txtProduto.setText(rs.getString(2));
                txtPreco.setText(rs.getString(3));
                txtCod.setEnabled(false);
                txtQtd.setText("1");
                txtQtd.requestFocus();
                btnAdicionarItem.setEnabled(true);
                btnCancelaItem.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(null, "Código não encontrado!!!");
                limpartextos();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setar() {
        int setar = tblPesqProd.getSelectedRow();

        txtCod.setText(tblPesqProd.getModel().getValueAt(setar, 0).toString());
        txtProduto.setText(tblPesqProd.getModel().getValueAt(setar, 1).toString());
        txtPreco.setText(tblPesqProd.getModel().getValueAt(setar, 2).toString());
        btnAdicionarItem.setEnabled(true);
        btnCancelaItem.setEnabled(true);
        txtQtd.setText("1");
        txtPesqProd.setText(null);
        pesquisaServProd();

    }

//    private void pesquisaCarrinho() {    }
    private void inserirNoCarrinho() {
        int qtd = Integer.parseInt(txtQtd.getText());
        Double prec = Double.valueOf(txtPreco.getText());
        Double valor = qtd * prec;

        if (txtProduto.getText().isEmpty() || txtQtd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todo os campos!!!");

        } else {
            meus_produtos = (DefaultTableModel) tblCarrinho.getModel();
            meus_produtos.addRow(new Object[]{
                txtCod.getText(),
                txtProduto.getText(),
                txtQtd.getText(),
                txtPreco.getText(),
                valor
            });
            qtdItens += qtd;
            subTotal += valor;
            limpartextos();
            txtSubtotal.setText(subTotal.toString());
            txtQtdItens.setText(String.valueOf(qtdItens));

//            txtQtdItens.setText(qtdItens.toString());
        }
    }

    private void excluirDoCarrinho() {
        int setar = tblCarrinho.getSelectedRow();
        int qtd = Integer.parseInt(tblCarrinho.getModel().getValueAt(setar, 2).toString());
        Double sub = Double.valueOf(tblCarrinho.getModel().getValueAt(setar, 4).toString());

        meus_produtos = (DefaultTableModel) tblCarrinho.getModel();
        meus_produtos.removeRow(tblCarrinho.getSelectedRow());
        btnRemoverItem.setEnabled(false);

        qtdItens -= qtd;
        subTotal -= sub;
        limpartextos();
        txtSubtotal.setText(subTotal.toString());
        txtQtdItens.setText(String.valueOf(qtdItens));

    }

    private void pagar() {
    }

    private void ativarBotao() {
        if (tblCarrinho.getRowCount() == 0) {
            btnPagar.setEnabled(false);
        } else {
            btnPagar.setEnabled(true);
        }
    }

    public void cancelarPedido() {
        for (int i = tblCarrinho.getRowCount(); i > 0; i--) {
            meus_produtos = (DefaultTableModel) tblCarrinho.getModel();
            meus_produtos.removeRow(0);
        }
        limpartextos();
        qtdItens = 0;
        subTotal = 0.0;
        txtQtdItens.setText(null);
        txtSubtotal.setText(null);
    }

    private void exclusaoCompleta() {
    }

    private void limpartextos() {
        txtCod.setText(null);
        txtQtd.setText(null);
        txtProduto.setText(null);
        txtPreco.setText(null);
        btnAdicionarItem.setEnabled(false);
        btnCancelaItem.setEnabled(false);
        txtCod.setEnabled(true);
        txtCod.requestFocus();
        ativarBotao();

    }

    public void inserirItensDaVenda() {
        int idRetorno;
        int estoque;
        for (int i = 0; i > tblCarrinho.getRowCount(); i++) {
            idRetorno = retornaUltimoIdVenda();
            int codProd = Integer.parseInt(tblCarrinho.getValueAt(i, 0).toString());
            int qtdComprada = Integer.parseInt(tblCarrinho.getValueAt(i, 2).toString());
            Double preco = Double.valueOf(tblCarrinho.getValueAt(i, 3).toString());
            Double valor = Double.valueOf(tblCarrinho.getValueAt(i, 4).toString());
            estoque = retornaQtdEstoque(codProd);
            int qtdAtualizada = estoque - qtdComprada;
            
            salvarItens(idRetorno, codProd, qtdComprada, preco, valor );
            baixaEstoque(qtdAtualizada, codProd);
            pesquisaServProd();

        }
    }

    public int retornaUltimoIdVenda() {

        int ultimoId = 0;

        String sql = "select max(id_venda) id_venda from tb_vendas";

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                ultimoId = rs.getInt("id_venda");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ultimoId;

    }

    public int retornaQtdEstoque(int id) {
        int quant = 0;

        String sql = "select * from tb_produtos where cod_prod=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);

            rs = pst.executeQuery();
            if (rs.next()) {
                quant = rs.getInt("qtd_prod");
                return quant;
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao retornar a quantidade do Estoque!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return quant;
    }
    
    public void salvarItens(int idVenda, int codProd, int qtd, double preco, double valor){
        String sql = "insert into tb_intens_da_venda(id_venda, cod_prod, qtd, preco, valor) values(?, ?, ?, ?, ?)";
        
        try {
            pst= conn.prepareStatement(sql);
            pst.setInt(1, idVenda);
            pst.setInt(2, codProd);
            pst.setInt(3, qtd);
            pst.setDouble(4, preco);
            pst.setDouble(5, valor);
            
            pst.execute();
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        
        
    }
    
    public void baixaEstoque(int qtdAtualizada, int codProd){
        String sql = "updete tb_produtos set qtd_prod=? where=?";
        
        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, qtdAtualizada);
            pst.setInt(2, codProd);
            
            pst.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

}
